import Head from "next/head";
import { useEffect, useState } from "react";

export default function Home() {
  let [response, setResponse] = useState<any>(null);
  useEffect(() => {
    

    fetch("/api/prompt")
      .then((res) => res.json())
      .then((json) => {
        setResponse(json.output);
      })
      .catch((err) => {
        console.error(err);
        alert("something be wrong. pls refroosh");
      });
  }, []);
  return (
    <>
      <Head>
        <title>???</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {response ? (
        <>
          <iframe
            srcDoc={response.replace("```html\n", "").replace("```", "")}
            style={{ width: "100%", height: "100vh", border: "none" }}
          ></iframe>
        </>
      ) : (
        <main>
          <div>
            <h1>generating strangeness...</h1>
            <a
              href="https://github.com/mikidoodle/zjierb.com"
              target="_blank"
              rel="noopener noreferrer"
              style={{
                color: "black",
              }}
            >
              code
            </a>
          </div>
            
        </main>
      )}
    </>
  );
}
